#!/usr/bin/python2.6



a=float(input("Enter 1st value : "))
b=float(input("Enter 2nd value : "))
#dec=a+b
dec=raw_input(" Chahte kya ho!!!")
#print(asd)

if dec=='+':
        print(a+b)
elif dec=='-':
        print(a-b)
elif dec=='*':
        print(a*b)
elif dec=='/':
        print(a/b)

#print(dec)
